### PR TITLE
Add support for consuming Matcher as a library through JitPack

### PR DESCRIPTION
**Pull request by kb-1000**

### CODE REVIEW

**Comment by i509VCB** [comment]
You may want to verify the jitpack jdk11 distribution actually includes javafx - given that is not bundled with the JDK.

I'd still discourage jitpack and we probably do need to publish this

**Comment by kb-1000** [comment]
As far as I can see, JavaFX is downloaded by the `org.openjfx.javafxplugin` Gradle plugin, and not even Oracle JDK 11 includes JavaFX.
So, I would think that's fine.

**Comment by kb-1000** [comment]
Also, the build log indicates it works: https://jitpack.io/com/github/kb-1000/matcher/patch-1-04eb6d585a-1/build.log

**Comment by i509VCB** [comment]
Hmm if that works then sure.

**Review by i509VCB — APPROVED** [review]

**Comment by i509VCB** [comment]
I think we are fine to merge this then.

**Pull request merged**
